
using System;

namespace LibMinecraft
{
    public enum McBlock
    {
        Air						= 0x00,
        Rock					= 0x01,
        Grass					= 0x02,
        Dirt					= 0x03,
        Cobblestone				= 0x04,
        Wood					= 0x05,
        Sapling					= 0x06,
        Adminium				= 0x07,
        Water					= 0x08,
        StationaryWater			= 0x09,
        Lava					= 0x0a,
        StationaryLava			= 0x0b,
        Sand					= 0x0c,
        Gravel					= 0x0d,
        GoldOre					= 0x0e,
        IronOre					= 0x0f,
        CoalOre					= 0x10,
        TreeTrunk				= 0x11,
        Leaves					= 0x12,
        Sponge					= 0x13,
        Glass					= 0x14,
        Cloth1					= 0x15,
        Cloth2					= 0x16,
        Cloth3					= 0x17,
        Cloth4					= 0x18,
        Cloth5					= 0x19,
        Cloth6					= 0x20,
        Cloth7					= 0x21,
        Cloth8					= 0x22,
        Cloth9					= 0x23,
        Cloth10					= 0x24,
        Flower					= 0x25,
        Rose					= 0x26,
        RedMushroom				= 0x27,
        BrownMushroom			= 0x28,
        Gold					= 0x29,
        Iron					= 0x2a,
        DoubleStoneSlab			= 0x2b,
        SingleStoneSlab			= 0x2c,
        RedBrickTile			= 0x2d,
        Tnt						= 0x2e,
        Bookshelf				= 0x2f,
        MossCoveredCobblestone	= 0x30,
        Obsidian				= 0x31,
        Torch					= 0x32,
        Fire					= 0x33,
        InfiniteWaterSource		= 0x34
    }
}